### ISSUE TITLE
Nautilus 43 support

### ISSUE THREAD

**Issue by yochananmarqos** [chr314/nautilus-copy-path#39] opened 2022-09-03 23:07 UTC
There are many changes with nautilus-python 4.0 and current Nautilus extensions will not work. See the [4.0.alpha](https://gitlab.gnome.org/GNOME/nautilus-python/-/tags/4.0.alpha) release notes for details about adopting the changes. GNOME 43 will be released in few weeks.

EDIT: See https://gnome.pages.gitlab.gnome.org/nautilus-python/nautilus-python-migrating-to-4.html

**Comment by TheRoarkster** [comment] 2022-11-24 18:19
I can confirm that under GNOME 43, `nautilus-copy-path` no longer works.  

This is one of my favorite apps.  It would be great if it could be updated to work.

**Comment by yochananmarqos** [comment] 2022-11-24 18:38
It's obsolete as Nautilus 43 has a Copy Location function now

**Comment by TheRoarkster** [comment] 2022-11-24 19:04
I guess I can see your take on it being obsolete, as there _is_ a "Copy Link" function.  But that capability is for files only and lacks the ability to "Copy Location" inside a directory to capture that directory's path.  Probably a niche use, and I understand not wanting to develop for a fringe case.  Thanks.

**Comment by yochananmarqos** [comment] 2022-11-24 19:19
I'm referring to the Copy Location option in the kebab menu at the end of the location bar.

Where are you seeing Copy Link?

**Comment by TheRoarkster** [comment] 2022-11-24 22:43
Ugh, you're right.  I was looking at the "Create Link" -- but I didn't use it.  It actually just creates a soft link.  

So, basically, there is no contextual menu support for this feature under GNOME 43.  That is a sad state of affairs.

**Comment by chr314** [comment] 2022-11-25 16:46
i see that @xiaohuirong is working on support for 43, i will wait for his pull request

https://github.com/xiaohuirong/nautilus-copy-path

**Comment by chr314** [comment] 2022-12-11 22:24
#41 merged

**Closed by chr314** 2022-12-11 22:24 UTC

**Comment by lukaszmoroz** [comment] 2022-12-16 12:55
Why was the support for shortcuts removed?

**Comment by chr314** [comment] 2022-12-16 13:56
yes because the way shortcuts work changed in gtk 4, but I'm working on it

**Comment by chr314** [comment] 2022-12-16 16:53
@lukaszmoroz just pushed a fix for the shortcuts, its kinda a hack but it works

**Comment by TheRoarkster** [comment] 2023-02-11 16:13
Confirming that the fix works.  Thanks!
